# Generated by Django 5.0 on 2024-01-13 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('start_work', models.TimeField(blank=True, null=True)),
                ('end_work', models.TimeField(blank=True, null=True)),
                ('launch_start_time', models.TimeField(blank=True, null=True)),
                ('launch_end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('TJS', 'Tajik Somoni'), ('UZS', 'Uzbekistani Soʻm')], default='TJS', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientBarberInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_appointed', models.PositiveIntegerField(default=0)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sartaroshxona.barber')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_worked', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_records', to='sartaroshxona.barber')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_services', to='sartaroshxona.barber')),
            ],
        ),
    ]
