# Generated by Django 5.0 on 2024-01-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='phone_number',
        ),
    ]
