# Generated by Django 5.0 on 2024-01-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0002_alter_barber_location_alter_barber_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
