# Generated by Django 5.0 on 2024-01-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0003_alter_barber_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/'),
        ),
    ]
