# Generated by Django 5.0 on 2023-12-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0003_barber_alter_service_master_delete_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
