# Generated by Django 5.0 on 2024-01-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0003_barber_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
