# Generated by Django 5.0 on 2023-12-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0004_barber_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='master',
            new_name='barber',
        ),
    ]
