# Generated by Django 5.0 on 2023-12-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0005_rename_master_service_barber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='end_work',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='launch_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='launch_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='start_work',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
