# Generated by Django 5.0 on 2024-01-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0005_alter_barber_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
