# Generated by Django 5.0 on 2024-01-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0005_barber_my_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='my_clients',
        ),
    ]
