# Generated by Django 5.0 on 2023-12-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0006_alter_barber_end_work_alter_barber_launch_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
    ]
