# Generated by Django 5.0 on 2024-01-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0007_clientbarberinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='worked_days',
            field=models.DateField(blank=True, null=True),
        ),
    ]
