# Generated by Django 5.0 on 2024-01-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0008_barber_payment_barber_payment_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='active_barber',
            field=models.BooleanField(default=False),
        ),
    ]
