# Generated by Django 5.0 on 2024-01-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0008_barber_daily_rate_barber_worked_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='worked_days',
        ),
    ]
