# Generated by Django 5.0 on 2024-01-11 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0009_remove_barber_daily_rate_remove_barber_worked_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_worked', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_records', to='sartaroshxona.barber')),
            ],
        ),
    ]
