# Generated by Django 5.0 on 2024-02-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0009_barber_active_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='bonus',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
