# Generated by Django 5.0 on 2024-02-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0010_barber_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='bonus',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(),
        ),
    ]
