# Generated by Django 5.0 on 2024-01-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0010_dailyworkrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkrecord',
            name='amount_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
