# Generated by Django 5.0 on 2024-02-11 11:16

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0011_alter_barber_bonus_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to='profile_images/'),
        ),
    ]
