# Generated by Django 5.0 on 2024-02-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sartaroshxona', '0013_alter_barber_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
