# Generated by Django 5.0 on 2024-02-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_appointment_appointment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('in_queue', 'В очереди'), ('confirmed', 'Подтверждено'), ('done', 'История')], default='in_queue', max_length=20),
        ),
    ]
