# Generated by Django 5.0 on 2024-01-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_appointment_total_duration_appointment_total_price'),
        ('sartaroshxona', '0004_alter_barber_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ManyToManyField(to='sartaroshxona.service'),
        ),
    ]
