# Generated by Django 5.0 on 2024-02-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('in_queue', 'In Queue'), ('confirmed', 'Confirmed'), ('done', 'History')], default='in_queue', max_length=20),
        ),
    ]
