# Generated by Django 5.0 on 2024-01-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_appointment_total_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Узбекистан', 'Узбекистан'), ('Таджикистан', 'Таджикистан'), ('Россия', 'Россия')], max_length=100)),
                ('uz_region', models.CharField(blank=True, choices=[('Ташкент', 'Ташкентская область'), ('Самарканд', 'Самаркандская область'), ('Бухара', 'Бухарская область'), ('Фергана', 'Ферганская область')], max_length=100, null=True)),
                ('tj_region', models.CharField(blank=True, choices=[('Душанбе', 'Душанбинская область'), ('Худжанд', 'Согдийская область'), ('Куляб', 'Кулябская область'), ('ГБАО', 'Горно-Бадахшанская автономная область')], max_length=100, null=True)),
                ('ru_region', models.CharField(blank=True, choices=[('Москва', 'Московская область'), ('Санкт-Петербург', 'Ленинградская область'), ('Новосибирск', 'Новосибирская область'), ('Екатеринбург', 'Свердловская область'), ('Самара', 'Самарская область'), ('Казань', 'Республика Татарстан'), ('Омск', 'Омская область'), ('Нижний Новгород', 'Нижегородская область'), ('Челябинск', 'Челябинская область'), ('Ростов-на-Дону', 'Ростовская область')], max_length=100, null=True)),
                ('uz_tashkent_city', models.CharField(blank=True, choices=[('Шар', 'Шар'), ('Янги Юнусобод', 'Янги Юнусобод'), ('Ёшлик', 'Ёшлик'), ('Чилонзор', 'Чилонзор'), ('Мирзо Улугбек', 'Мирзо Улугбек'), ('Узбекистан', 'Узбекистан'), ('Яссака', 'Яссака'), ('Янгиабад', 'Янгиабад')], max_length=100, null=True)),
                ('tj_dushanbe_state', models.CharField(blank=True, choices=[('Истиклол', 'Истиклол'), ('Шаро', 'Шаро'), ('Бодмордар', 'Бодмордар'), ('Амирабад', 'Амирабад')], max_length=100, null=True)),
            ],
        ),
    ]
