# Generated by Django 5.0 on 2024-01-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_delete_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('in_queue', 'In Queue'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('canceled', 'Canceled')], default='in_queue', max_length=20),
        ),
    ]
