# Generated by Django 5.0 on 2024-02-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('sartaroshxona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mfavorite_barbers',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='sartaroshxona.barber'),
        ),
    ]
