# Generated by Django 5.0 on 2024-01-15 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_city_customuser_coutry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='coutry',
            new_name='country',
        ),
    ]
