# Generated by Django 5.0 on 2024-02-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_mfavorite_barbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mfavorite_barbers',
            new_name='favorite_barbers',
        ),
    ]
