# Generated by Django 5.0 on 2024-01-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_coutry_customuser_country'),
        ('sartaroshxona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_barbers',
            field=models.ManyToManyField(related_name='favorited_by', to='sartaroshxona.barber'),
        ),
    ]
