# Generated by Django 5.0 on 2024-01-07 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fruit_vegetable_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables')], max_length=20)),
                ('selected_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_fruit', to='main.fruit')),
                ('selected_vegetable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_vegetable', to='main.vegetable')),
            ],
        ),
    ]
