# Generated by Django 5.0 on 2024-01-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_foodselection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodSelection',
        ),
    ]
