# Generated by Django 5.0 on 2024-01-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_foodselection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Vegetable',
        ),
    ]
