# Generated by Django 5.0 on 2024-01-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_fruit_delete_vegetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='times_appointed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
