# Generated by Django 5.0 on 2024-01-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_customuser_favorite_barbers'),
        ('sartaroshxona', '0004_alter_barber_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='ads/')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_barbers',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='sartaroshxona.barber'),
        ),
    ]
