# Generated by Django 5.0 on 2024-01-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customuser_times_appointed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='times_appointed',
        ),
    ]
