# Generated by Django 5.0 on 2024-01-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ads_alter_customuser_favorite_barbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='profile_image',
            new_name='ad',
        ),
    ]
