# Generated by Django 5.0 on 2024-01-29 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_profile_image_ads_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad',
            field=models.ImageField(default=datetime.datetime(2024, 1, 29, 8, 43, 29, 680715, tzinfo=datetime.timezone.utc), upload_to='ads/'),
            preserve_default=False,
        ),
    ]
