# Generated by Django 5.0 on 2024-01-29 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_ads_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad',
            field=models.ImageField(upload_to='images_of_ads/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
