# Generated by Django 5.0 on 2024-02-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_ads_city_ads_country_ads_district_ads_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agreement',
            field=models.BooleanField(default=True),
        ),
    ]
